version: '3.8'

services:
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/kidashi/Dockerfile.prod
    entrypoint: /app/docker/kidashi/server-entrypoint.prod.sh
    env_file:
      - ./envs/.env
    volumes:
      - static_volume:/app/frontend/static
      - media_volume:/app/media
    expose:
      - 8000
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=BrnQ@Ng3B0x#4Xv8B7K0848177325LxLttX
      - POSTGRES_DB=kidashi
    ports:
      - "5432:5432"

  always_on_task:
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/kidashi/Dockerfile.prod
    entrypoint: /app/docker/kidashi/worker-entrypoint.sh
    volumes:
      - static_volume:/app/frontend/static
      - media_volume:/app/media
    depends_on:
      - web
      - redis
  schedule_task:
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/kidashi/Dockerfile.prod
    entrypoint: /app/docker/kidashi/scheduler-entrypoint.sh
    volumes:
      - static_volume:/app/frontend/static
      - media_volume:/app/media
    depends_on:
      - web
      - redis

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379

  nginx:
    restart: always
    container_name: nginx-proxy
    build: docker/nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d
      - static_volume:/app/frontend/static
      - media_volume:/app/media
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web

  acme-companion:
    image: nginxproxy/acme-companion
    env_file:
      - ./envs/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme:
