# Generated by Django 5.2.5 on 2025-09-11 12:59

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CircleActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('activity_type', models.CharField(choices=[('MEMBER_ADDED', 'Member Added'), ('MEMBER_REMOVED', 'Member Removed'), ('LOAN_DISBURSED', 'Loan Disbursed'), ('PAYMENT_MADE', 'Payment Made'), ('STATUS_CHANGED', 'Status Changed'), ('VOTING_INITIATED', 'Voting Initiated')], max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, help_text='Additional context data for the activity', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'circle_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CircleMembershipVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_phone', models.CharField(max_length=20)),
                ('vote', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=10)),
                ('voting_deadline', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the vote', null=True)),
            ],
            options={
                'db_table': 'circle_membership_votes',
            },
        ),
        migrations.CreateModel(
            name='TrustCircle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('circle_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('loan_eligibility', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not Eligible'), ('UNDER_REVIEW', 'Under Review')], default='UNDER_REVIEW', max_length=20)),
                ('status', models.CharField(choices=[('FORMING', 'Forming'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='FORMING', max_length=20)),
                ('max_members', models.PositiveIntegerField(default=10, help_text='Maximum number of women allowed in this circle', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)])),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trust_circles',
                'ordering': ['-created_at'],
            },
        ),
    ]
