# Generated by Django 5.2.5 on 2025-09-19 14:22

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CircleActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('activity_type', models.CharField(choices=[('CIRCLE_CREATED', 'Circle Created'), ('CIRCLE_UPDATED', 'Circle Updated'), ('CIRCLE_ACTIVATED', 'Circle Activated'), ('CIRCLE_SUSPENDED', 'Circle Suspended'), ('CIRCLE_CLOSED', 'Circle Closed'), ('MEMBER_ADDED', 'Member Added'), ('MEMBER_REMOVED', 'Member Removed'), ('MEMBER_SUSPENDED', 'Member Suspended'), ('MEMBER_REACTIVATED', 'Member Reactivated'), ('VOTE_INITIATED', 'Vote Initiated'), ('VOTE_SUBMITTED', 'Vote Submitted'), ('VOTE_COMPLETED', 'Vote Completed'), ('VOTE_EXPIRED', 'Vote Expired'), ('VOTE_CANCELLED', 'Vote Cancelled'), ('OTP_SENT', 'Otp Sent'), ('OTP_RESENT', 'Otp Resent'), ('OTP_VERIFIED', 'Otp Verified'), ('LOAN_APPLIED', 'Loan Applied'), ('LOAN_APPROVED', 'Loan Approved'), ('LOAN_REJECTED', 'Loan Rejected'), ('LOAN_DISBURSED', 'Loan Disbursed'), ('LOAN_REPAID', 'Loan Repaid'), ('ADMIN_ACTION', 'Admin Action'), ('VENDOR_ACTION', 'Vendor Action'), ('SYSTEM_ACTION', 'System Action')], max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, help_text='Additional context data for the activity', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'circle_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CircleMembershipVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('voter_one_otp', models.CharField(blank=True, max_length=10, null=True)),
                ('voter_two_otp', models.CharField(blank=True, max_length=10, null=True)),
                ('voter_three_otp', models.CharField(blank=True, max_length=10, null=True)),
                ('voter_one_generated_otp', models.CharField(blank=True, max_length=10, null=True)),
                ('voter_two_generated_otp', models.CharField(blank=True, max_length=10, null=True)),
                ('voter_three_generated_otp', models.CharField(blank=True, max_length=10, null=True)),
                ('voter_one_vote', models.CharField(blank=True, choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=10, null=True)),
                ('voter_two_vote', models.CharField(blank=True, choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=10, null=True)),
                ('voter_three_vote', models.CharField(blank=True, choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('voting_deadline', models.DateTimeField(help_text='Deadline for completing the vote')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_votes', models.PositiveIntegerField(default=0)),
                ('rejected_votes', models.PositiveIntegerField(default=0)),
                ('result_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'circle_membership_votes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustCircle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('circle_name', models.CharField(max_length=255)),
                ('loan_eligibility', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not Eligible'), ('UNDER_REVIEW', 'Under Review')], db_index=True, default='UNDER_REVIEW', max_length=20)),
                ('status', models.CharField(choices=[('FORMING', 'Forming'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='FORMING', max_length=20)),
                ('max_members', models.PositiveIntegerField(default=10, help_text='Maximum number of women allowed in this circle', validators=[django.core.validators.MaxValueValidator(10)])),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trust_circles',
                'ordering': ['-created_at'],
            },
        ),
    ]
