# Generated by Django 5.2.5 on 2025-09-11 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trust_circle', '0001_initial'),
        ('vendor', '0001_initial'),
        ('woman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleactivity',
            name='affected_woman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='woman.woman'),
        ),
        migrations.AddField(
            model_name='circleactivity',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='circlemembershipvote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='woman.woman'),
        ),
        migrations.AddField(
            model_name='trustcircle',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_circles', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='circlemembershipvote',
            name='trust_circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trust_circle.trustcircle'),
        ),
        migrations.AddField(
            model_name='circleactivity',
            name='trust_circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trust_circle.trustcircle'),
        ),
        migrations.AddIndex(
            model_name='trustcircle',
            index=models.Index(fields=['vendor', 'status'], name='trust_circl_vendor__d91018_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trustcircle',
            unique_together={('vendor', 'circle_name')},
        ),
        migrations.AddIndex(
            model_name='circlemembershipvote',
            index=models.Index(fields=['trust_circle', 'candidate_phone'], name='circle_memb_trust_c_06400f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='circlemembershipvote',
            unique_together={('trust_circle', 'voter', 'candidate_phone')},
        ),
        migrations.AddIndex(
            model_name='circleactivity',
            index=models.Index(fields=['trust_circle', 'activity_type'], name='circle_acti_trust_c_0c0028_idx'),
        ),
    ]
