# Generated by Django 5.2.5 on 2025-09-24 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_circle', '0001_initial'),
        ('vendor', '0002_guarantor_vendor_onboardingactivitylogs_vendor_and_more'),
        ('woman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trustcircle',
            name='trust_circl_status_c916aa_idx',
        ),
        migrations.AddField(
            model_name='circleactivity',
            name='affected_woman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='woman.woman'),
        ),
        migrations.AddField(
            model_name='circleactivity',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='circleactivity',
            name='trust_circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trust_circle.trustcircle'),
        ),
        migrations.AddField(
            model_name='circlemembershipvote',
            name='candidate_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_votes', to='woman.woman'),
        ),
        migrations.AddField(
            model_name='circlemembershipvote',
            name='initiating_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='circlemembershipvote',
            name='trust_circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_votes', to='trust_circle.trustcircle'),
        ),
        migrations.AddField(
            model_name='circlemembershipvote',
            name='voter_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_as_voter_one', to='woman.woman'),
        ),
        migrations.AddField(
            model_name='circlemembershipvote',
            name='voter_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_as_voter_three', to='woman.woman'),
        ),
        migrations.AddField(
            model_name='circlemembershipvote',
            name='voter_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_as_voter_two', to='woman.woman'),
        ),
        migrations.AddField(
            model_name='trustcircle',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trust_circles', to='vendor.vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='circlemembershipvote',
            unique_together={('trust_circle', 'candidate_member', 'status')},
        ),
        migrations.AlterUniqueTogether(
            name='trustcircle',
            unique_together={('vendor', 'circle_name')},
        ),
        migrations.AddIndex(
            model_name='circleactivity',
            index=models.Index(fields=['trust_circle', 'activity_type'], name='circle_acti_trust_c_0c0028_idx'),
        ),
        migrations.AddIndex(
            model_name='circlemembershipvote',
            index=models.Index(fields=['trust_circle', 'candidate_member'], name='circle_memb_trust_c_49985b_idx'),
        ),
        migrations.AddIndex(
            model_name='trustcircle',
            index=models.Index(fields=['vendor', 'status'], name='trust_circl_vendor__d91018_idx'),
        ),
    ]
