# Generated by Django 5.2.5 on 2025-10-08 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_circle', '0002_remove_trustcircle_trust_circl_status_c916aa_idx_and_more'),
        ('vendor', '0006_vendor_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustcircle',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trust_circles', to='vendor.vendor'),
        ),
    ]
