# Generated by Django 5.2.5 on 2025-09-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_circle', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleactivity',
            name='activity_type',
            field=models.CharField(choices=[('CIRCLE_CREATED', 'Circle Created'), ('MEMBER_ADDED', 'Member Added'), ('MEMBER_REMOVED', 'Member Removed'), ('LOAN_DISBURSED', 'Loan Disbursed'), ('PAYMENT_MADE', 'Payment Made'), ('STATUS_CHANGED', 'Status Changed'), ('VOTING_INITIATED', 'Voting Initiated')], max_length=20),
        ),
    ]
