# Generated by Django 5.2.5 on 2025-10-14 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust_circle", "0003_alter_trustcircle_vendor"),
        ("woman", "0005_alter_woman_vendor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="circlemembershipvote",
            name="approved_votes",
        ),
        migrations.RemoveField(
            model_name="circlemembershipvote",
            name="rejected_votes",
        ),
        migrations.RemoveField(
            model_name="circlemembershipvote",
            name="result_message",
        ),
        migrations.AddField(
            model_name="circlemembershipvote",
            name="voter",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="votes_cast", to="woman.woman"),
        ),
    ]
