# Generated by Django 5.2.5 on 2025-10-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trust_circle", "0004_remove_circlemembershipvote_approved_votes_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="circlemembershipvote",
            name="circle_memb_status_9fc8e0_idx",
        ),
        migrations.RemoveField(
            model_name="circlemembershipvote",
            name="voter_one",
        ),
        migrations.RemoveField(
            model_name="circlemembershipvote",
            name="voter_one_generated_otp",
        ),
        migrations.RemoveField(
            model_name="circlemembershipvote",
            name="voter_one_otp",
        ),
        migrations.RemoveField(
            model_name="circlemembershipvote",
            name="voter_one_vote",
        ),
        migrations.RemoveField(
            model_name="circlemembershipvote",
            name="voter_three",
        ),
        migrations.RemoveField(
            model_name="circlemembershipvote",
            name="voter_three_generated_otp",
        ),
        migrations.RemoveField(
            model_name="circlemembershipvote",
            name="voter_three_otp",
        ),
        migrations.RemoveField(
            model_name="circlemembershipvote",
            name="voter_three_vote",
        ),
        migrations.RemoveField(
            model_name="circlemembershipvote",
            name="voter_two",
        ),
        migrations.RemoveField(
            model_name="circlemembershipvote",
            name="voter_two_generated_otp",
        ),
        migrations.RemoveField(
            model_name="circlemembershipvote",
            name="voter_two_otp",
        ),
        migrations.RemoveField(
            model_name="circlemembershipvote",
            name="voter_two_vote",
        ),
        migrations.RemoveField(
            model_name="circlemembershipvote",
            name="voting_deadline",
        ),
    ]
