# Generated by Django 5.2.5 on 2025-10-17 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trust_circle", "0005_remove_circlemembershipvote_circle_memb_status_9fc8e0_idx_and_more"),
        ("woman", "0006_alter_woman_trust_circle"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="circlemembershipvote",
            unique_together={("trust_circle", "candidate_member")},
        ),
    ]
