# Generated by Django 5.2.5 on 2025-10-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trust_circle", "0006_alter_circlemembershipvote_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="circlemembershipvote",
            unique_together=set(),
        ),
    ]
