# Generated by Django 5.2.5 on 2025-09-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('ASSET_REQUEST', 'Asset Request'), ('GUARANTOR_APPROVAL', 'Guarantor Approval'), ('OTHER', 'Other')], max_length=50)),
                ('otp', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'otp_codes',
                'indexes': [models.Index(fields=['purpose', 'expires_at'], name='otp_codes_purpose_61a8ab_idx')],
            },
        ),
    ]
