# Generated by Django 5.2.5 on 2025-09-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='channel',
            field=models.CharField(default='sms', max_length=20),
        ),
        migrations.AddField(
            model_name='otp',
            name='recipient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='subject_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(max_length=128),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['purpose', 'subject_id'], name='otp_codes_purpose_7634b5_idx'),
        ),
    ]
