# Generated by Django 5.2.5 on 2025-10-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0002_otp_channel_otp_recipient_otp_subject_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="purpose",
            field=models.CharField(
                choices=[("ASSET_REQUEST", "Asset Request"), ("VOTER_VALIDATION", "Voter Validation"), ("GUARANTOR_APPROVAL", "Guarantor Approval"), ("OTHER", "Other")], max_length=50
            ),
        ),
    ]
