# Generated by Django 5.2.5 on 2025-09-27 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='metadata',
        ),
    ]
