upstream kidash {
    server web:8000;
}

server {
    listen 80;

    location / {
        proxy_pass http://eft_bridge;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /static {
      alias /app/frontend/static/;
      add_header Access-Control-Allow-Origin *;
    }

    location /media {
      alias /app/media;
      add_header Access-Control-Allow-Origin *;
    }
}
