# Generated by Django 5.2.5 on 2025-09-24 11:58

import common.functions
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        ('trust_circle', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Woman',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('other_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,15}$')])),
                ('account_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Account number must be valid', regex='^\\+?1?\\d{9,15}$')])),
                ('maximum_balance', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('tier', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('annual_income', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('residential_address', models.CharField(blank=True, max_length=255, null=True)),
                ('stage', models.CharField(choices=[('NEW_USER', 'New User'), ('VENDOR_ONBOARDING', 'Vendor Onboarding'), ('MOBILE_NUMBER_REGISTRATION', 'Mobile Number Registration'), ('EMAIL_REGISTRATION', 'Email Registration'), ('PASSWORD_REGISTRATION', 'Password Registration'), ('BVN_VERIFICATION', 'Bvn Verification'), ('LOCATION', 'Location'), ('IDENTIFICATION', 'Identification'), ('PEP', 'Pep'), ('SOURCE_OF_INCOME', 'Source Of Income'), ('BUSINESS_INFORMATION', 'Business Information'), ('PIN', 'Pin'), ('ATTESTATION', 'Attestation')], default='VENDOR_ONBOARDING', max_length=100)),
                ('private_key', models.CharField(default=common.functions.gen_random_key, max_length=255)),
                ('nin', models.CharField(blank=True, db_index=True, help_text='National Identification Number', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='NIN must be exactly 11 digits', regex='^\\d{11}$')])),
                ('bvn', models.CharField(blank=True, db_index=True, help_text='Bank Verification Number', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='BVN must be exactly 11 digits', regex='^\\d{11}$')])),
                ('cba_customer_id', models.UUIDField(blank=True, db_index=True, help_text='Customer ID from the bank system', null=True, unique=True)),
                ('repayment_status', models.CharField(choices=[('ON_TIME', 'On Time'), ('LATE', 'Late'), ('DEFAULTED', 'Defaulted'), ('PAID_OFF', 'Paid Off'), ('UNDER_REVIEW', 'Under Review'), ('NOT_APPLICABLE', 'Not Applicable'), ('ONGOING', 'Ongoing')], db_index=True, default='NOT_APPLICABLE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('LEFT_CIRCLE', 'Left Circle')], default='ACTIVE', max_length=20)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.country')),
                ('geo_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.georegion')),
                ('lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.localgovernment')),
                ('next_of_kin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_of_kin', to='woman.nextofkin')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.state')),
                ('trust_circle', models.ForeignKey(help_text='Trust circle this woman belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='women', to='trust_circle.trustcircle')),
                ('vendor', models.ForeignKey(help_text='Vendor who onboarded this woman', on_delete=django.db.models.deletion.CASCADE, related_name='women', to='vendor.vendor')),
            ],
            options={
                'db_table': 'women',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'status'], name='women_vendor__3feecc_idx'), models.Index(fields=['trust_circle', 'status'], name='women_trust_c_d914e7_idx')],
            },
        ),
    ]
