# Generated by Django 5.2.5 on 2025-09-11 12:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trust_circle', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Woman',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nin', models.CharField(blank=True, help_text='National Identification Number', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='NIN must be exactly 11 digits', regex='^\\d{11}$')])),
                ('bvn', models.CharField(blank=True, help_text='Bank Verification Number', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='BVN must be exactly 11 digits', regex='^\\d{11}$')])),
                ('cba_customer_id', models.CharField(blank=True, help_text='Customer ID from the bank system', max_length=50, null=True, unique=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('repayment_status', models.CharField(choices=[('ON_TIME', 'On Time'), ('LATE', 'Late'), ('DEFAULTED', 'Defaulted'), ('PAID_OFF', 'Paid Off'), ('UNDER_REVIEW', 'Under Review'), ('NOT_APPLICABLE', 'Not Applicable'), ('ONGOING', 'Ongoing')], default='NOT_APPLICABLE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('LEFT_CIRCLE', 'Left Circle')], default='ACTIVE', max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('trust_circle', models.ForeignKey(help_text='Trust circle this woman belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='women', to='trust_circle.trustcircle')),
                ('vendor', models.ForeignKey(help_text='Vendor who onboarded this woman', on_delete=django.db.models.deletion.CASCADE, related_name='women', to='vendor.vendor')),
            ],
            options={
                'db_table': 'women',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'status'], name='women_vendor__3feecc_idx'), models.Index(fields=['trust_circle', 'status'], name='women_trust_c_d914e7_idx'), models.Index(fields=['repayment_status'], name='women_repayme_10cc10_idx'), models.Index(fields=['phone'], name='women_phone_6fdd82_idx'), models.Index(fields=['nin'], name='women_nin_9af5c0_idx'), models.Index(fields=['bvn'], name='women_bvn_6028af_idx'), models.Index(fields=['cba_customer_id'], name='women_cba_cus_e0ba55_idx')],
            },
        ),
    ]
