<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-09-16 15:44
=======
# Generated by Django 5.2.5 on 2025-09-16 15:01
>>>>>>> e225df80d2943e7cf0649740a547f072574186a6

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woman',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='woman',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
