# Generated by Django 5.2.5 on 2025-09-24 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_localgovernment_state_state_region'),
        ('trust_circle', '0002_remove_trustcircle_trust_circl_status_c916aa_idx_and_more'),
        ('vendor', '0002_guarantor_vendor_onboardingactivitylogs_vendor_and_more'),
        ('woman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='woman',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.country'),
        ),
        migrations.AddField(
            model_name='woman',
            name='geo_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.georegion'),
        ),
        migrations.AddField(
            model_name='woman',
            name='lga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.localgovernment'),
        ),
        migrations.AddField(
            model_name='woman',
            name='next_of_kin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_of_kin', to='woman.nextofkin'),
        ),
        migrations.AddField(
            model_name='woman',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.state'),
        ),
        migrations.AddField(
            model_name='woman',
            name='trust_circle',
            field=models.ForeignKey(blank=True, help_text='Trust circle this woman belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='women', to='trust_circle.trustcircle'),
        ),
        migrations.AddField(
            model_name='woman',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor who onboarded this woman', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='women', to='vendor.vendor'),
        ),
        migrations.AddIndex(
            model_name='woman',
            index=models.Index(fields=['vendor', 'status'], name='women_vendor__3feecc_idx'),
        ),
        migrations.AddIndex(
            model_name='woman',
            index=models.Index(fields=['trust_circle', 'status'], name='women_trust_c_d914e7_idx'),
        ),
    ]
