# Generated by Django 5.2.5 on 2025-09-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woman', '0002_woman_country_woman_geo_region_woman_lga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woman',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
