# Generated by Django 5.2.5 on 2025-10-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woman', '0003_alter_woman_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woman',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='woman',
            name='lga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='woman',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
