# Generated by Django 5.2.5 on 2025-10-08 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0006_vendor_rejection_reason'),
        ('woman', '0004_alter_woman_country_alter_woman_lga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woman',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor who onboarded this woman', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='women', to='vendor.vendor'),
        ),
    ]
