# Generated by Django 5.2.5 on 2025-10-16 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust_circle", "0005_remove_circlemembershipvote_circle_memb_status_9fc8e0_idx_and_more"),
        ("woman", "0005_alter_woman_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="woman",
            name="trust_circle",
            field=models.ForeignKey(
                blank=True, help_text="Trust circle this woman belongs to", null=True, on_delete=django.db.models.deletion.CASCADE, related_name="trust_circle_women", to="trust_circle.trustcircle"
            ),
        ),
    ]
