# Generated by Django 5.2.5 on 2025-10-22 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_circle', '0005_remove_circlemembershipvote_circle_memb_status_9fc8e0_idx_and_more'),
        ('woman', '0006_alter_woman_trust_circle'),
    ]

    operations = [
        migrations.AddField(
            model_name='woman',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='woman',
            name='trust_circle',
            field=models.ForeignKey(blank=True, help_text='Trust circle this woman belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='women', to='trust_circle.trustcircle'),
        ),
    ]
