# Generated by Django 5.2.5 on 2025-10-08 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cba_customer_id', models.UUIDField(db_index=True, help_text='Customer ID from the bank system', unique=True)),
                ('event_type', models.CharField(choices=[('VENDOR_STATUS_CHANGED', 'Vendor status updated'), ('TRUST_CIRCLE_CREATED', 'Trust circle created'), ('MEMBER_JOINED', 'New member joined'), ('ASSET_APPROVED', 'Asset approved'), ('ASSET_DENIED', 'Asset denied'), ('FUNDING_CREDITED', 'Funding credited')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
