# Generated by Django 5.2.5 on 2025-10-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_inappnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappnotification',
            name='cba_customer_id',
            field=models.UUIDField(db_index=True, help_text='Customer ID from the bank system'),
        ),
        migrations.AlterField(
            model_name='inappnotification',
            name='event_type',
            field=models.CharField(choices=[('VENDOR_STATUS_CHANGED', 'Vendor status updated'), ('TRUST_CIRCLE_CREATED', 'Trust circle created'), ('MEMBER_JOINED', 'New member joined'), ('ASSET_APPROVED', 'Asset approved'), ('ASSET_DENIED', 'Asset denied'), ('FUNDING_CREDITED', 'Funding credited'), ('WOMAN_ONBOARDED', 'Woman onboarded')], max_length=50),
        ),
    ]
