# Generated by Django 5.2.5 on 2025-10-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0004_alter_inappnotification_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inappnotification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("VENDOR_STATUS_CHANGED", "Vendor status updated"),
                    ("TRUST_CIRCLE_CREATED", "Trust circle created"),
                    ("MEMBER_JOINED", "New member joined"),
                    ("ASSET_APPROVED", "Asset approved"),
                    ("ASSET_DENIED", "Asset denied"),
                    ("FUNDING_CREDITED", "Funding credited"),
                    ("WOMAN_ONBOARDED", "Woman onboarded"),
                    ("VENDOR_ONBOARDED", "Vendor onboarded"),
                    ("ASSET_WARNING", "Asset Warning"),
                ],
                max_length=50,
            ),
        ),
    ]
