# Generated by Django 5.2.5 on 2025-09-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingactivitylogs',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_activities', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='state',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.georegion'),
        ),
        migrations.AddField(
            model_name='localgovernment',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.state'),
        ),
    ]
