# Generated by Django 5.2.5 on 2025-09-24 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
        ('vendor', '0002_guarantor_vendor_onboardingactivitylogs_vendor_and_more'),
        ('woman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_assets', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='asset',
            name='woman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_requested', to='woman.woman'),
        ),
        migrations.AddField(
            model_name='assetactivity',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.asset'),
        ),
    ]
