# Generated by Django 5.2.5 on 2025-09-24 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        ('woman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='woman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets_requested', to='woman.woman'),
        ),
        migrations.AddField(
            model_name='assetactivity',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset'),
        ),
    ]
