# Generated by Django 5.2.5 on 2025-09-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_asset_vendor_asset_woman_assetactivity_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='items_requested',
            field=models.JSONField(blank=True, default=list, help_text='List of items the woman wants to purchase'),
        ),
        migrations.AddField(
            model_name='asset',
            name='loan_product_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Loan Product ID from the bank system for the asset financing', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='loan_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Loan ID from the bank system for the asset financing', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('QUERIED', 'Queried'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='REQUESTED', max_length=20),
        ),
    ]
