# Generated by Django 5.2.5 on 2025-09-25 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_asset_items_requested_asset_loan_product_id_and_more'),
        ('vendor', '0002_guarantor_vendor_onboardingactivitylogs_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetactivity',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.vendor'),
        ),
    ]
