# Generated by Django 5.2.5 on 2025-09-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_assetactivity_performed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('QUERIED', 'Queried'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], db_index=True, default='REQUESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetactivity',
            name='activity_type',
            field=models.CharField(choices=[('ASSET_REQUEST', 'Asset Request'), ('SYNC_START', 'Sync started with PayRep'), ('SYNC_SUCCESS', 'Sync success with PayRep'), ('SYNC_FAILED', 'Sync failed with PayRep'), ('SYNC_WARNING', 'Sync warning (partial success)'), ('LOAN_DISBURSED', 'Loan disbursed to woman'), ('LOAN_REPAYMENT', 'Loan repayment recorded'), ('LOAN_DEFAULT', 'Loan defaulted'), ('LOAN_CLOSED', 'Loan fully repaid / closed')], max_length=20),
        ),
    ]
