# Generated by Django 5.2.5 on 2025-10-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_alter_asset_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='loan_product_id',
        ),
        migrations.AddField(
            model_name='asset',
            name='loan_product_code',
            field=models.CharField(blank=True, db_index=True, help_text='Loan Product Code from the bank system for the asset financing', null=True),
        ),
    ]
