# Generated by Django 5.2.5 on 2025-10-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_remove_asset_loan_product_id_asset_loan_product_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='loan_product_code',
            new_name='product_code',
        ),
    ]
