# Generated by Django 5.2.5 on 2025-10-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_rename_loan_product_code_asset_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('QUERIED', 'Queried'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('CLOSED', 'Closed')], db_index=True, default='REQUESTED', max_length=20),
        ),
    ]
