# Generated by Django 5.2.5 on 2025-10-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_alter_asset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('QUERIED', 'Queried'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('CLOSED', 'Closed'), ('RUNNING', 'Running')], db_index=True, default='REQUESTED', max_length=20),
        ),
    ]
